### ISSUE TITLE
怎么实现渐变填充

### ISSUE THREAD

**Issue by PaofYueng** [AAChartModel/AAChartKit-Pro#11]
在readme中标识了 Support color layer gradient effects，但没给出示例，请问如何实现渐变填充。

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/470
* https://github.com/AAChartModel/AAChartKit/issues/636
* https://github.com/AAChartModel/AAChartKit/issues/830
* https://github.com/AAChartModel/AAChartKit/issues/921
* https://github.com/AAChartModel/AAChartKit/issues/1459

**Comment by AAChartModel** [comment]
以上使用示例都可以在AAChartKit 的 demo 中找到. 由于 AAChartKit-Pro 采用完全兼容 AAChartKit 的设计, 所以所有有效的 AAChartKit 示例都是有效的 AAChartKit-Pro 示例. 下载 AAChartKit 的 demo 运行查看即可. 

AAChartKit 传送门:
* https://github.com/AAChartModel/AAChartKit
