### ISSUE TITLE
pod导入会crash

### ISSUE THREAD

**Issue by xbindai** [AAChartModel/AAChartKit-Pro#14]
pod 'AAChartKit-Pro', '0.0.6' ，运行后crash，如下图⬇️

<img width="1169" alt="iShot_2023-12-18_19 38 59" src="https://github.com/AAChartModel/AAChartKit-Pro/assets/84165254/f74f9fa4-e2a4-4d26-9bcd-f43a10d6cbe8">

<img width="1763" alt="iShot_2023-12-18_19 40 11" src="https://github.com/AAChartModel/AAChartKit-Pro/assets/84165254/210e3e48-8c0d-4f75-a3b7-3de6776b3b63">

**Comment by AAChartModel** [comment]
请将这里的 

```objc
    NSString *bundlePath = [resourcePath stringByAppendingPathComponent:@"/AAChartKitLib.bundle"];

```

改成 
```objc
    NSString *bundlePath = [resourcePath stringByAppendingPathComponent:@"/AAChartKit-Pro.bundle"];

```

再试试.
