### ISSUE TITLE
404 Error: AAChartKit-Swift-Pro URL

### ISSUE THREAD

**Issue by ampodobas** [AAChartModel/AAChartKit-Pro#4]
In the readme, a broken link is present: "The Swift version of AAChartKit can be found here:
[https://github.com/AAChartModel/AAChartKit-Swift-Pro](https://github.com/AAChartModel/AAChartKit-Swift-Pro)"

**Comment by AAChartModel** [comment]
AAChartKit-Swift-Pro (Beta Version ) visibility is public now.
