### ISSUE TITLE
会和AACahartKit保持同步更新吗？

### ISSUE THREAD

**Issue by zachary-zhang** [AAChartModel/AAChartKit-Pro#8]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by AAChartModel** [comment]
暂时没有同步

**Comment by zachary-zhang** [comment]
有计划吗 发现了一个在标准库没问题，pro有问题的bug

**Comment by AAChartModel** [comment]
具体是什么 bug?
