### ISSUE TITLE
请问桑基图的内容名称怎样指定颜色？

### ISSUE THREAD

**Issue by sonwa** [AAChartModel/AAChartKit-Pro#9]
请问桑基图的内容名称怎样指定颜色？见只有一个颜色数组，想指定名称是那个固定颜色要怎样设置？

**Comment by sonwa** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/1425134/204490150-45093b51-b185-4fb1-a0b9-4d1474a10f09.png">

应该是长条颜色和线颜色，怎样设置？？不是一个数组然后变成随机那种，是对应固定色

**Comment by AAChartModel** [comment]
你需要的是类似于这种效果?
![sankey-levels](https://user-images.githubusercontent.com/16357599/204517685-0d6047e2-8936-42f0-b1a0-d230bbf9aee9.png)

**Comment by sonwa** [comment]
你图这个应该是一排固定一只颜色。我是想按key-name设置颜色。网页设置
 { name: '巴西', itemStyle: { color: 'rgba(61,220,132,1)' } },
  { name: '英国', itemStyle: { color: 'rgba(66,133,244,1)' } },
  { name: '美国', itemStyle: { color: 'rgba(2,192,87,1)' } },
  { name: '法国', itemStyle: { color: 'rgba(52,132,87,1)' } }


  { source: '巴西', target: '英国', value: 1 },
  { source: '巴西', target: '美国', value: 5 },
  { source: '美国', target: '法国', value: 10 }

就是想问一下iOS要设置类似itemStyle指定key的颜色要怎样设？

**Comment by sonwa** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/1425134/204695506-d94f6179-5b5f-4b98-af25-33a82c54e07c.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/1425134/204695576-a77a6d02-6781-4b3a-a398-483431569fbc.png">

试了keys加多一个color线条颜色是可以设置，但那个长条块颜色设置不到。请问长条块是那个属性控制的？

**Comment by AAChartModel** [comment]
试试 AASeriesElement 的 nodes 属性

```objc
AAPropStatementAndPropSetFuncStatement(strong, AASeriesElement, NSArray  *, nodes)
```

参考文档:
* https://api.highcharts.com/highcharts/series.sankey.nodes.color

**Comment by sonwa** [comment]
设了nodes可以了，谢谢。
